### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by devonwesley**

### CODE REVIEW

**Comment by Anasauce** [comment]
@Jusdev89 We still have to figure out that bug that is occurring I think it has something to do with the import/export issue

**Comment by Anasauce** [comment]
@Jusdev89  That error looks familiar to when that wasn't working before

**Comment by devonwesley** [comment]
I fixed it. its working now. Pull it down and let me know if its working for you. @Anasauce

**Comment by Anasauce** [comment]
!(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQMAAADCCAMAAAB6zFdcAAABIFBMVEX////9ujGOJY1UMBl9NSB/NSBSMBmFAIT/vTL/wDL/wTL/vjL/uy+NIYxSLhmMHYuzmV1NKRhRKxFGIxd4NB9PKxiJEIhJJRhGGABNJABJHQBnMhxZMRqtlmBsMx1IGwBEEwBZNBrw7evq2urdxN369fpiMhtCHxfGncb17fVPKAuoY6fMlCqNYCCrnZamdCTn1efmsEDd19Q+AACVNpSFcGWcSJtpQhyjWKLSy8fCn1W4grfWuda+j76Yh37Oqs5oSzuteyXvsC9dPCiWaCLBiyi+tK7coSyvca9yWEp6UB7Ko1HhrUS0qKHYqUnkpy3Rpk17UR5/aFyRfnSzebI5FBY0AACOYiGgkIeeTp3El8NtRhzn4+E+CwBgQjFBCgAc2/KlAAAafklEQVR4nO1dC1vaytYWRki4RgIEgiAXuUhEsYgi3kVRaWut2nOq1a3//198a00SMrlgq+2W8Xx9936qJCFmvbNm3WYmMzPzF3/xF3/xF2+I5nMna83F6u7B0t55bfI1iwd/+pHeHN3uwQQBD6SYIgAURREmy/lDEJ6l8R1gV4gJys6i16lNyW8i1p3w9WpX8Uvn9kPvjpJuDERUhLtd15lFwW9BqHp9uXku4NcFlsKqoLjvxRcOluwfDUElwb/naL89heEgtul1L0XXFGnLOlaFGwrPmY/poykIO+xnf2wspSIsV71PUUVYc95qbXOsKJaWVOkxxe+6miMsS35h2fp4INjkZOlZs52ytTWi9k1gzIWpJVXjSzFh79+W5NXYxWdUuqaq1mxtbRfzm2TjwN7pZ2bO7ezpJqBqHVQ2Pe3s9NHUu7gUM55vydbl/WwvrjkocFp/O30xPx6rCswx6Rl/Ok0sS6aq0g5skzNmb+iqvStgW9ttpr2vKAcOCoBoLm3CrvXYtJFsll+we7Rlpx74lR373ZbsJDhYUza5DBOaNpH3ZmoK0252dwHnnBTAJQ6PZ6NJWrZ9gzW8PMHetMK3HeapnWZ/14MDxR5azDTtFtV2c07dwq6jh0vMU9vtIeDO1RWQBMcd3TbDuJvAaaTY9GhZq90c9qtpScf2F6el/+FJgiRxaQ0BW89w4BLOcpqxrkWC7gFtN/VQF6XLpTVELC4LXvpNn3rHebEluFJluHNlTk0p5ryZsMxzsgABvuuJqe7eOa+0UkZImu8YRXBlTi6TILj45Ay7XY8O7LKHbOAgfYPskJHQ1dP37HfkNDi04UBymQW3XEzKCBaerSM4XeiMrdICuadnmYE31H4IdhYUd8sxYTAGyJusa3BlQk2LA8nPrTV0oLljM44eFSIrZaQGgM2sHJkT4ty8Wrrj2Ro6AC7iWaksmaWdWo0NFlyZE+CZU1xjzRLT7fRZWy8JgmJzqYozCrbMhTOf4B1McOOyie6UkYVTUsttCG/29H8GPyxFcLZsbUIWYF7uyJwsxmJv9/h/BIzpdwY+bG6lACTJHgxK9stjk+7DPdjGdtgyJmVU9g6W9na+nbPe0REGWeZA4rRkMBlMKmSPEFgvoBh93zbcYh9zOmBDyncGpoBib0AmNLaiwq5NEdiIwjIHLo/BPdheL7GmnlWQsfljKo+SIjCKwJSXncaSf7AqzzYsq/aW19SPgviCcrezu+h5Oa/Fo2fAFIjYnrwn0PF2HdbhLhyVtvZ2nekC03O8h2W5xvkzI+vN5uLi2lqVCZ4O9ryH1Jl4yp1OcQ9bWeDVj89o0ztLFxBsx1d+vPomkE4YqvDe0gXEWIvB1Lmqab+K2trBzhZNrGLvLV1A0LQJ5I8tH/xuT25Wl867ztGH94Al8ADK1tIaq8KV09O+7eP+9cZqx33CC++wK8xUu3tVx3OvFrPFrLZqfHrYyBVVTcuVNiq3cKJ03HnzZ3x77JdIEP7LHlbw02pJC5L6wsJCUCuqJBgk8tPPVOH9o/9EyMJsqh7U1A4SEiQLAcR8kJB8KkWCcrEy07ndByYqqxsX+pcqlek+9B/GoRxMBQKzgYWgnO2vZoP12UCqnp8PzIJyzMKJfFB+vCmpaunwVstp2WMg5Dqoaoen037wP4f+U3A+kEpREoiqBuvwWx7En4fPQMTsLCiErIFKBGWVALRRPwcfibz+P0LCQ2XmWiOzC0EqOmo/QanhBxygtCzAv9AfQFVSeSAmBcLnSDA/Xw/Kx9N++j+B/nFJ3ceWr4PMqAn1IMpMf+Jn/IV+np3Hs/gb5Qn0IxDIE3Xaz/8nIMug2ih9HuTShc+j9kPLp2apXQykAjbAmSCqCPSdOpFHhxvvuT9UoBf0SyQPLZ4HSbHdUXZsbWAhlVpYmJ+v1+t5E/D7/AJlJpXPY99ZAIWQZa30+F6jh/5htlRSaeOnFlKo7Cls8FkUvQ7dnoI4QI/l6/MpVIYgxA8YPIBpfJ9esr8u60IGqeSztPEX5qnwTskNxA1QKvKgEvi1FAQVJHcxbXFehWOZgF6DQqMTQAZS83lD+nQik0mOkUkkEmlkoEzRK5fjcDYRh4vruqWoE+1m2uK8Bp1SkEaCs6DVaAIMAuLpRDLzsX00bLVaZ2eXl5cDCh9CpAiHRN/gbHjSAxoguF6YRQ7U22nL8xqs5sAABsC0oScAdQ6SeCKZJL2V9nAQDkUiusBiFOBzISqKodBlmySRhXngoPgeXUNFw0AIYkFQhlno0CSdJCetgRiGZvYQ2oOGqBgSW/fJNMRKhDy9Q5vYIRAVoKOHuGcB2jLduGpFwr8mvY6vn7B3hM/uQRcgSJi2QC/H6hNQQCMhqgTxxtVlWPx1+UELPhQKX6LYKcKtcoaQd1deqBwWiRkHp1AJ4q2XMYD4NPc5Gh18GERD4kmDkPXVn/9djtAvQWi8MKsbQ7AEmStf5KUMoD2IRj8VCgWgItzKpElpY9pyvQC36zTf0TMCoCB5En6BGbDRsD0HKHyIRga9DFEPpy3ZL+O2RKNjagsgBybJ9mspQKOAJHyN+qJh6A/a47Rl+1Ws6xkyjYzAqWVACwa+VytCYa5QoAFUeNgg6nvwDpWLEVaBIMDNQ4QcAI+QuAr5QJBXKoIv+uXrF0pgNBo+SpLi/rQl/ClWSzlZrxEE4McsGIN4mXbqwudXdwc9ihxsf/KFr9JknfPic+WxSKNBysF8sI49IXkpDgrUrL1WEwx1KBS2I4MMBF7TlvJZVDQNYqHvrQT1CXrxtDEM+YCDwqffowD0YK4wFw0NoTdwHSaMgILyZThcjhuVsjxJrISpXfv6uxTAXdAwhnpxrsuLOIaSGUR84ZU0CRihQXygm7NXUCBGQqGIM7YUW6AIHBdTRjJJguaHRJODOskchV4lPwjrax2dnBydhRwshHtxmd8goVMi8R5QMIwnjDETQhLUtQ1eQcGgnEwkEplkrxV2KcITt9nTrQpqEAl9h+zG7ArplfCXwmtcQnRA0kX18LGYAxtrzzQi5Ti/FaVHmcR94TZ4xrw+TDIfhK7xtfCa8Ch0nzvGslHlQpWTKyHbqaOMfDhtWSfgoUQSJ+FBA5OlFB0uypPkIPph7pMrTBY9jJ29rYdJiIkrN8fH+w/HcqPFXhyFGKHEaUnptEiSZ+i/6xgmY8pEQC88XEJ40DpqH535Qr6JCPX+6cx0cqpMsredElBr+/7HdJbT0uKNFi+LoaMEyaP08G8qGL93Fw1E30kmmQFjR47ESbogXiYPZ2awFAeYeUx8t3EQGWZUTpOGQxnaK/Q9jaOEoAfzaBKvXG0dHZQzcjanZotysjeYQII4zN7gAB0iVxml7XoADHFqECo5kmyJoXscIJqdXYC8ccGLg1AvnRv1KzMPp4e5RG+CHoSOsrcmB3JFhiDDfj4ez3FpECA6SAyiYjmuJ0w0WUivODkQhw3VHC7aL2ZOvG1CqF28malQDoq3/WzyzK4voXK8xGXyeJHDAMmXxNKBPrA278EB2DMZrz69Bau2oWW8o6fIUQaSw9X1nFoaQR/rOe4CypbjMm+60dB8Y1/QKfDmwJdR4ekfSFbNBiuVXHLoaREgFkTL37kApjbURsthWcNXaY3L6upIzgwjaLNxss2sPpHEg4NGEbT4EacZqRszo0R7goOE07THV65zmZWw42T4JMFnykAIdlt4PIODhdREDjpP+jD7zEZukkEYJuXj1YuLjaLWuHKfha7Co1EEC5Ye+MSzhjHMngrOe3OQO8VoSudgsh6EVhrpXDabbfRa7itECMRKHKZN/Wy8J/oivXg9YAwrePaFUFm7njmlFj+7ivZg0siLeHR1f78CqbPHBeJZkstB6NNi/GNYvGwEU6ZJHMcHrO0PnSQg8dWyuVxpY+Ya/MLEjDISDuP4tNcpzBhUDh3Dqgp5stiyOJg1ORiwmbN4+R+i9mf6Fxf9zkidFB/8FHHCo2O4URMoUCJOdCWgHMQ/hnzRD7bqQeioQUrHN/sbxyU5Xf6JqFhN81KFUC/O40j8hoYc6CkTGAM66ZTmTNEP9oGF8DCeTGiaFk9PzhcooiHx7Kh90m75XFdBpEU4nLs6ktHGR1pJzBYCNHUGDsoicPDF3ucjYuvkY6/XWxl693ZDBcKDdryBU7Ua5MxpF8EDG/EDVzikHECYSLOFBawnYlUZHnjgKquLIbR3z0xHgAvOVhoJc7Ze0mk5MZbmsIzyiBxgeKBXU6lhhLAJn/hloysiEHB5VB4zAEg4I0VxmOExQKAchFbSedMt0LIybcHtX+NAFEXwh77L4ff8P/88jY6ZeZvO1AoDhKyROT7yEyhQDnwJyzXSUaYGhM/RbW+JI4AQQu8Yg8uzYXull2yU1rMbpxUcrBgj2bL3G/FyHCR11p8eZjQ+nMQjVpHOGsSiAIdY8OGjn9wJcth3NjwCtNvtk5OVq/tyPNNoJLOlf4ry6EJX8muN4cCRXkYHCXPmbqek3WyofCyEOpTT3y0OAkbyjBWg6BfnqLvoO0lSk68jrWVLpafS8Wj/onOaMxNCmx44U+xBmtAKwk35RiOaxslUZuBgBTjQJ+bTGSgYJGHMEP3gcAziIMEYPEK0m9N+p2LexqwQMRS4+oJPJHTmbuVJ1rUly4UejOT0x7DuFkD2oL4yxwiWHUZRTMdtM9WZsBeyaqNcauaWOgdnHhxgLcZIwkluSlLbca3F70O+MobKuGCHzkeaDWIu6fPZx5nQudthtSIagRzWzTsqe0HCaVEMPZgxKeDDN2zg6EKk1cARFpyabMzGSaAF27ZlDOFe3MEBUR/0m/Rpu6rHG6Msezp+76wk+YhuD/QsnJBjLjIosE3EhzMPcMUKoavXqGO4BMfw1W4QGk4KiKzShqxouhGQNdl2OnPkDJbRL9CvHOpXqlxwcKuixmLwkscFWiljvSJ1jh/mGA6iAzcH0B0OV09XHaJbHLi6wqUZI6HZkLVc8WHa8iNWc9jmoY9pumxtXEFI4PDIoDBgn9+LA1CFnOp1HCloO7uCFSsDB/LjaJWP3IGOuIq+dLw+rqEE6AQE4CA6x0QIUW8OJiNedhoDX6idMIqqGxpHhYR+lnpxJlieTwUCBLNniBTZtElMvoyDhit1xgEGfe1rp8TTCp+HEskMI2I5XjeCxAVczkhnIPiin1nviDO2XkLB0KOwXI5r1/hHwYCUuDAFFJUcwcTxCuTTDUJqfiFgGsUBOxtngkGYRMGRyy/qNVVo/j4YUU7SJR3HmDCIECBgIclYyQgGQR9BmGNrSeGVxM9l15HOeGgBnZYFbmEfgwOuBl9psEwDBFpCMMwCSX9Eo7htD5fTrijJG8nepVfhGceZtFuCfiTHRWBg4kaL9yJYTMvT0gFNnuBnPO2jc41ZFx85+6XekEhMmKmCM7cpA7yt6bjIkbQv6ssYS/lJykif0WNGP9hnrYdayZ9pQjyTORlMGn0o69dopetpS21DBWcnXooDzBwDZkGRRknUIDimbIfOys7EyYZ0stweTFr7gsEoyZWy5JonW4DDTDma5ou9RJDUrVpSimA6iQsYHPmz7yQzwTLGE8n0SssXmliFRHNQ7PD2rpjKIc3zsLI8uE+Q8QwEWlPEMcXo14Iz5g8PTuK4mtkmPi6E7p20fM8uA8RRpsNpi+zEA4GkUTumOa4YPkkbK9rq80za5F7GEg37Wie9RDKZwbIaLoJPlD+2W4PIZALoXEdMmPibijMCCop9PXOkCwz0iiom0Jgy4OzCgecaDjEUGpy1hkftI1wEfzkQn18IPfi0va0nCxwFhzoq0BFyHZo1QZODVVwImK+8gbjZSBnm5iZZOFGvsEcmztgca8GnAt4FAmWO8iQDkC5hMo+T8/ShptSYgxSdtIx1lG2XQXgxop8L2x+iNEjko3bGYF+lpW3IGOI9hoMFutJ1XGD/3TVdSAIYBF8YZ4FOW2QXiKwvMDqUaZMnjfQZ8wV9EQOdhVD48loOotGBtUI0wuVanhuVlOkv+yqmz6HviXogwAw3EX30+dUL2yDzLhRMLYr64nGuFvf1+51K/xqCI1n/WCLxj+EoGMV8fcGcmEUNAg4PFLYjtE1fTME2XfBsJF2hj2mS5UgNOv/NlkpZbfyGikqODjSHThJG/gzuMR8IzOtDZbpj+PxSq2Cs+Z6jWiSGrjKEq+mZ/XUjvDNf2rOh6WVwyOqCNH+m7wRcCOIE1kEBOIA2femSX3AGlAP8NXzZA3r5WtC1asa4xrBvX1/YFi4To7gcNPSgJWJz0ijBNI3e78LxAvCGy4FECK4bcWMYih+cmsPjZvhOsAIqYtF0nrqF+XwqoAcI4BuRgw9zxphT9MPXr18mT060aQL8HxlPztEOpymxC53/Ggxopn6u5kh6JRy+TxN8zZfxPrwgFsejn3R1jhhagIau8GsLgEEDQmfteINWYlWefAJiQ8thy4yu1zX9AC67yEB+/x98Xnz7AX37IdCCvWDOWvQbHeid/KcxA8gfHgxXEsbsJG39GqjnLVe4UWXIX8zZAxgrYIhwuaLPMKjPzxNj9oDu3Qbbc3RmjsHB3HNTlaj8rZNyI2PW4tWNDticp3W+LMLMxbrMmumHJ0iRwvi+sxW0X4S+Ha1MGx6jHMx6aAcAa48seHcGEaemhUUqf5KWXzW1VJIJLmajMw44f4kgKEL642U4IoZb9w19vg2dl/WZhon41qc5ahSjvs+QCH91iA6mLxzx6ZOzEklaYZHV7JO8sdqvjGRSWkX3C26It95gB1qEdLJ3dOYL03lX7Xb7MoJ68Gls442mB8ugvzQOBQfJcV7a0clVL5/BNwnS5gf5S4e3fb3VHyAaKa2iAeL+FbMX+IaweCKZuG8PL310/r0uqf6KPGNCnj4tfwByYwVl5WOvnEjSgpIx8iBravEpNzLlp7jNGQV1/opITqwePtG3IscTmWSmfL/SPhrS9yS2EEOckdc++X4FUpfT9B2SKLg55iKD7Lls6Ul9vN4/dYWDh0Y4wvNrMEw8XFyrpaIqG1XSDPO+TPidvjEzTV8WagmOkpdK6uNoY/9iPEfNiYp+y3fzxunO6f6IQEaVUz0ml4DUKHYR5S5pIPjN7UW///BTa/8g5zR1naOs8RdQ6fQvbm82wLdRaRHZrFo+Phxdg9irp/2JTT4Jtxu3fPsEF/RhkFM1h9MpdUz7kd4Y/cdcdnRxMSoS+f+b6Cb66zK+NT4nk6f31YP/IPQ51zL4+Xf5WuQ/ghwNZ0arp/+CEas1Fxeb/G9RU8HkJvdvzBmrftukO775t5Z437zsOCdr/0LBY8kvmDufSoqwzDcLlZvR4R+vfq51BfvWrwIn+1o2D6prb9M7D+wM0E3c+Nj7ew17p+Lf3DrfWdr9N+n44bUpstTlgQR92+5YTJIkxUbH62w3GP21tUWPfQoPvPeFlpybQ04Du85nQzoUg47u1vlL9i1c/IGb9FGzv3xg52Ft0tbYCgd7HrObVboQk17wiNVNa/N3+KLwjTX7kssWjG3CwcQ7vhV+PMeBfTte3MC0untwsLS05/ZqzTunyWPN/s4zf2X6u1t+e3YLe3Y73qau5rjBudup7Qoe91G6TfOrLDVKLBZTLMaUnTcTdgKWf8KB1eJLVlu6trndm2DxFH3jW2YDaGGLbn/b3O2Oj01dEe4mdlS9kaznY3fzduxQO4ECIEvfBJrZ3tfSq2WTBGXaFqH7LAdMg1dZOe2PPcHv6SQssk7BtsvzlkGNtWn6lOB/lgNms/dzyfu4Y8975w2w4cd21+4DmuPDbyWsN2qCJMUm0yCN7VXTLii7Re0zqiRsYqcxbU5s0/7HTTMx5f2vazvny5vdGMZEliQWKZbOO+IIa7N3Z0+IWd+OGf7DJElx7PluKhAv+6DXmuPmjN11JXNP9/HTbdobm3FoNjVQBP9d1+BTiRlEmRe49vo2v+TgZnoYN7Su5xj5Vw9Mt+CMdS1jydrKmPCDillFxyecm5dIthszMJzS1B2DibFlczl/hCuUGrcpcybmHzf0ucB4wXEE7byr4Rm44WCcPHm5qpor1h0/N9MVmGBiZofRe7uCMTA6GDd9YRzLSefuk+4IwPSONeuMMEkU05a47L+hILzYRCtolr65T3pEk0ajW8FBzD/p1mZowSZgCNPIuGzltDDWacVd5bMEZaJevfEsYylNzH3MTMPJkmlKXH1kSrBiIGdrzTCpr2RZQMM7Wm5hsmUbU2hPEc3DXp1vKlh7Rpba2LB3rcuMoO+5740xDsjZYLlmat5EO/LW2LVSWdcjWS5jhzWB1MIt/kJfYAo1VuWh2Z0YNkwLO2MlZ8JgA2aCh/T4HXG05TUn20TWeSj+H2vNZnNtZ1x38+h7U8KWxYHTg1lNDQbcMgiGd7SC6GdcHFNYp7kJFmzNz67IaWqw2tflqcaRA0aQTO6ke0erRhSTmBjp3D6SNjm35CY4YFNjV2nLz3pNpligPz2TSUjdMX07giQsM51q0T3IZNxk6tXEMRhJnBWNKuMK7jaZ/NHwdHdWzCApS8hCrbqJymFjoepdaFGmXUNiwKq44xRTdY3F2HqLkVzZi2zK5tad32x0Sdgas+AazOGNAsbUOdPGpncDUo3Ru7y9NB2zDadIeiUJUVVcJWzBIyyfHqyEwFnwemYQxoiKmsozNUlmoKq5ZTcKisRLzkxRsx5Ocoyudb1qbMalhiZP6Ov0EtvAMh2Oi9E7SUJsb9rjCnYsjueHOKN3Rr5YtwvenVHomFkw8Ozr9GZ+h6NdXNrqSori39yp8sUAPNr51qZfwYE0yZE2ntsMRa1WY6tqY9++6+36lK5XVlxrcjslq9ZcrO4ufbvzHgOw8gF27HDs3Bf9brMRE5Z5lfVFYHymmUsxozKMD6ntCIqDAT8v+eBvossUTQy93mIsAptbNHckw+LR6Qddroz+b2AxhiMNigSijdNCK8OEk7acr1bd2+rG4OLuMvezD1+CWnNtd2lnuSuNhwuwe2BDC9LmtyVXno12800f8C3RHMd7oBjd86Xq4v+urD9Fc/f/s/R/8Rd/8Rc84/8A2hQxWhsGQWAAAAAASUVORK5CYII=)  Thanks @Jusdev89 Whooo! So glad that is finally working

**Comment by Anasauce** [comment]
yay

**Comment by Anasauce** [comment]
@Jusdev89 ^^ merging now!

**Pull request merged**
